kind: pipeline
name: default

steps:
- name: backend
  image: golang:1.13
  commands:
    - export GO111MODULE=on
    - export GOPROXY=https://athens.bsprague.com
    - CGO_ENABLED=0 GOOS=linux go build -ldflags '-extldflags "-static" -s -w' -o cmd/codenames-server/server github.com/bcspragu/Codenames/cmd/codenames-server
    - go test ./...
- name: frontend
  image: docker.bsprague.com/node
  commands:
    - cd web/frontend
    - yarn
    - yarn build
  volumes:
    - name: nodecache
      path: /drone/src/web/frontend/node_modules
- name: docker
  image: plugins/docker
  settings:
    repo: docker.bsprague.com/codenames
    registry: docker.bsprague.com
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: cmd/codenames-server/Dockerfile
    context: cmd/codenames-server/
- name: scp
  image: appleboy/drone-scp
  settings:
    host: prod.bsprague.com
    username:
      from_secret: ssh_username
    key:
      from_secret: ssh_key
    target: /var/www/codenames.ai
    source: web/frontend/dist/*
    rm: true
    strip_components: 3
- name: ssh
  image: appleboy/drone-ssh
  settings:
    host: prod.bsprague.com
    username:
      from_secret: ssh_username
    key:
      from_secret: ssh_key
    script:
      - sudo systemctl restart codenames.service

volumes:
- name: nodecache
  host:
    path: /tmp/nodecache

branches: master
