pipeline:
  backend:
    group: build
    image: golang:1.11
    commands:
      - go build -o cmd/codenames-server/server github.com/bcspragu/Codenames/cmd/codenames-server
      - go test ./...
    volumes:
      - /tmp/gocache:/go/pkg/mod
  frontend:
    group: build
    image: docker.bsprague.com/node
    commands:
      - cd web/frontend
      - yarn
      - yarn build
    volumes:
      - /tmp/nodecache:/drone/src/github.com/bcspragu/Codenames/web/frontend/node_modules
  docker:
    image: plugins/docker
    repo: docker.bsprague.com/codenames
    registry: docker.bsprague.com
    secrets: [ docker_username, docker_password ]
    dockerfile: cmd/codenames-server/Dockerfile
    context: cmd/codenames-server/
  scp:
    image: appleboy/drone-scp
    host: prod.bsprague.com
    secrets: [ ssh_username, ssh_key ]
    target: /var/www/codenames.ai
    source: web/frontend/dist/*
    rm: true
    strip_components: 3

branches: master
