pipeline:
  backend:
    group: build
    image: golang:1.11
    commands:
      - go build github.com/bcspragu/Codenames/cmd/codenames-server
      - go test ./...
  frontend:
    group: build
    image: docker.bsprague.com/node
    commands:
      - cd web/frontend
      - yarn
      - yarn build
  scp:
    image: appleboy/drone-scp
    host: prod.bsprague.com
    secrets: [ ssh_username, ssh_key ]
    target: /var/www/codenames.ai
    source: web/frontend/dist/*
    rm: true
    strip_components: 3

branches: master
